package apicontract

import (
	"fmt"
	"regexp"
	"strings"
)

// browserOnlyOperations are the OperationIDs a UI action never calls
// through a typed client function — ADR-028's own "Ngoại lệ duy nhất là
// bootstrap/static asset của browser" (internal/delivery/parity's
// BrowserBootstrap map is the CLI/application-side twin of this same
// exemption). "bootstrap" is read once from window.__AW_BOOTSTRAP__, never
// fetched; "staticAsset" is loaded natively by the browser's own
// <script src>/<link href>; "uiShell" (V7-05A) is the SPA client-side
// router's own server-side fallback route — a direct browser navigation
// hits it, application code never does. Generating a client function for
// any of the three would be actively misleading, not just redundant.
var browserOnlyOperations = map[string]bool{
	"bootstrap":   true,
	"staticAsset": true,
	"uiShell":     true,
}

// tsClientPathParamPattern matches a Go 1.22 net/http.ServeMux wildcard
// segment ("{id}", "{projectId}") the way every path-parameterized route in
// this registry names one — see route.go's own RouteDescriptor.Path doc
// reference. It deliberately does NOT match the "{path...}" remainder
// syntax: no operation in this registry's client-facing set (everything
// except browserOnlyOperations above) uses it. (Named distinctly from
// routeinventory_test.go's own pathParamPattern, which serves a different,
// test-only substitution purpose and does not need a capture group.)
var tsClientPathParamPattern = regexp.MustCompile(`\{([a-zA-Z0-9_]+)\}`)

// GenerateTypeScriptClient renders V7-02's own "API client từ contract"
// requirement as real TypeScript source: one typed function per non-
// browser-only Operation in c, using ONLY the information the contract
// itself carries — never inventing a field/shape Fields does not actually
// list. A SchemaRef that is Opaque, or has zero Fields, becomes `unknown`
// (honest about not knowing the shape) rather than `any` (which would
// silently defeat type-checking at every call site) or a fabricated
// interface. Output is fully deterministic given the same Contract: field
// order follows SchemaRef.Fields (itself stable — Go struct reflection
// order — see contract.go's own TestContract_IsDeterministic), and
// c.Operations is already sorted by OperationID by Build.
//
// This lives in the apicontract package itself, not a separate cmd/ tool
// or subpackage: apicontract already owns "what a client of this contract
// looks like" (its own doc comment: "a later task can still walk this
// artifact to hand-generate a real OpenAPI document") and generating this
// way lets its own test suite reuse buildRealContract/buildRealRegistry
// directly instead of duplicating the ~90-line real-infrastructure
// composition helper in a second binary.
func GenerateTypeScriptClient(c Contract) []byte {
	var b strings.Builder
	b.WriteString(tsClientPreamble)

	for _, op := range c.Operations {
		if browserOnlyOperations[op.OperationID] {
			continue
		}
		writeOperation(&b, op)
	}

	return []byte(b.String())
}

const tsClientPreamble = `// Code generated by internal/delivery/httpapi/apicontract.GenerateTypeScriptClient.
// DO NOT EDIT — regenerate via internal/delivery/httpapi/apicontract's own
// TestGeneratedTypeScriptClient_MatchesGoldenFixture (see that test's doc
// comment for the exact regeneration recipe). A change to this file that
// was not produced by regenerating from the real Contract will be
// overwritten and re-fail that test on the next contract change.
//
// Every SchemaRef the real Contract could not describe beyond its own
// top-level field list (see internal/delivery/httpapi/apicontract's own
// "why a custom JSON contract, not full OpenAPI 3.x" doc comment) becomes
// "unknown" here, never a fabricated shape or "any" — narrowing an
// "unknown" at the call site is the caller's own, explicit decision.

export interface RequestOptions {
  /**
   * The per-start session token from window.__AW_BOOTSTRAP__.token. Required
   * for every mutation (anything but GET/HEAD); ignored for a query. Callers
   * MUST keep this in memory only — never write it to a URL, log, or
   * localStorage/sessionStorage (ADR-016).
   */
  token?: string;
  /**
   * Idempotency key for a mutation (ignored for a query). Omit to have one
   * generated per call; pass one explicitly only to retry the exact same
   * logical attempt rather than mint a new one.
   */
  idempotencyKey?: string;
  /**
   * If-Match for an update-shaped mutation (ignored for a query or a
   * create). The server's ETagFromVersion wraps a prior response's own
   * version field in double quotes, so pass that same version wrapped in
   * double quotes, e.g. version 3 becomes a 3-character string: a double
   * quote, the digit 3, and a closing double quote. Required by any route
   * whose handler calls httpapi.RequireIfMatch; omitting it there fails
   * with ErrIfMatchRequired.
   */
  ifMatch?: string;
  /** Extra raw query-string parameters this contract does not itself type. */
  query?: Record<string, string>;
  signal?: AbortSignal;
}

export interface ApiErrorDetail {
  field: string;
  message: string;
}

export class ApiError extends Error {
  constructor(
    public status: number,
    public code: string,
    message: string,
    public details?: ApiErrorDetail[],
  ) {
    super(message);
  }
}

async function request<TResponse>(
  method: string,
  path: string,
  body: unknown,
  opts: RequestOptions,
): Promise<TResponse> {
  const url = new URL(path, window.location.origin);
  if (opts.query) {
    for (const [key, value] of Object.entries(opts.query)) {
      url.searchParams.set(key, value);
    }
  }

  const headers: Record<string, string> = {};
  const isSafeMethod = method === "GET" || method === "HEAD";
  if (!isSafeMethod) {
    if (opts.token) {
      headers["X-Aw-Session-Token"] = opts.token;
    }
    // Every mutation requires an Idempotency-Key (httpapi.RequireIdempotencyKey
    // on the server side); a fresh one per call is correct here for the same
    // reason the aw CLI's own mutations generate one when --idempotency-key
    // is omitted — a caller that wants to retry the SAME logical attempt
    // (rather than mint a new one) passes its own key back via opts.idempotencyKey.
    headers["Idempotency-Key"] = opts.idempotencyKey ?? crypto.randomUUID();
    if (opts.ifMatch) {
      headers["If-Match"] = opts.ifMatch;
    }
  }
  if (body !== undefined) {
    headers["Content-Type"] = "application/json";
  }

  const res = await fetch(url, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
    signal: opts.signal,
  });

  if (!res.ok) {
    const errBody = await res.json().catch(() => null);
    throw new ApiError(
      res.status,
      errBody?.error?.code ?? "UNKNOWN",
      errBody?.error?.message ?? res.statusText,
      errBody?.error?.details,
    );
  }
  if (res.status === 204) {
    return undefined as TResponse;
  }
  return (await res.json()) as TResponse;
}

`

// writeOperation emits one operation's request/response type aliases (when
// SchemaRef actually carries fields) and its typed client function.
func writeOperation(b *strings.Builder, op Operation) {
	pathParams := tsClientPathParamPattern.FindAllStringSubmatch(op.Path, -1)
	isGet := op.Method == "GET" || op.Method == "HEAD"

	requestTypeName := ""
	if !isGet {
		requestTypeName = writeSchemaType(b, op.OperationID, "Request", op.RequestSchema)
	}
	responseTypeName := writeSchemaType(b, op.OperationID, "Response", op.ResponseSchema)

	fmt.Fprintf(b, "// %s %s (scope: %s)\n", op.Method, op.Path, op.ScopeKind)
	fmt.Fprintf(b, "export function %s(", op.OperationID)

	args := make([]string, 0, len(pathParams)+2)
	for _, m := range pathParams {
		args = append(args, fmt.Sprintf("%s: string", m[1]))
	}
	if !isGet {
		args = append(args, fmt.Sprintf("body: %s", requestTypeName))
	}
	args = append(args, "opts: RequestOptions = {}")
	b.WriteString(strings.Join(args, ", "))
	fmt.Fprintf(b, "): Promise<%s> {\n", responseTypeName)

	urlExpr := goPathToTemplateLiteral(op.Path, pathParams)
	if isGet {
		fmt.Fprintf(b, "  return request<%s>(%q, %s, undefined, opts);\n", responseTypeName, op.Method, urlExpr)
	} else {
		fmt.Fprintf(b, "  return request<%s>(%q, %s, body, opts);\n", responseTypeName, op.Method, urlExpr)
	}
	b.WriteString("}\n\n")
}

// writeSchemaType emits `interface <OperationID><Suffix> { ... }` when ref
// actually lists fields, else nothing — and returns the TypeScript type
// name the caller should reference (the interface name, or "unknown").
func writeSchemaType(b *strings.Builder, operationID, suffix string, ref SchemaRef) string {
	if ref.Opaque || len(ref.Fields) == 0 {
		return "unknown"
	}
	typeName := operationID + suffix
	// OperationID starts lower-case (e.g. "listWorkItems"); a type name
	// should not, by TypeScript convention.
	typeName = strings.ToUpper(typeName[:1]) + typeName[1:]

	fmt.Fprintf(b, "export interface %s {\n", typeName)
	for _, f := range ref.Fields {
		key, omitempty := jsonWireKey(f)
		if key == "-" {
			continue // encoding/json excludes this field from the wire entirely.
		}
		optional := ""
		if omitempty {
			optional = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", key, optional, goFieldTypeToTS(f.Type))
	}
	b.WriteString("}\n\n")
	return typeName
}

// jsonWireKey parses f.JSONTag exactly the way encoding/json itself does —
// Field.JSONTag carries the RAW `json:"..."` tag value verbatim (see
// contract.go's own reflection loop: `f.Tag.Get("json")`, never split), so
// a tag like "parentJoinPolicy,omitempty" is one comma-separated string,
// not a bare key. Splitting it here (rather than at the point Contract is
// built) keeps Contract itself a faithful, unopinionated mirror of the raw
// reflected tag — this generator is the one place that needs the parsed
// form. Returns the wire key encoding/json will actually use (falling back
// to f.Name for an empty/absent tag, exactly like the standard library
// does) and whether "omitempty" was one of the tag's options.
func jsonWireKey(f Field) (key string, omitempty bool) {
	tag := f.JSONTag
	name, options, _ := strings.Cut(tag, ",")
	if name == "" {
		name = f.Name
	}
	for _, opt := range strings.Split(options, ",") {
		if opt == "omitempty" {
			omitempty = true
		}
	}
	return name, omitempty
}

// goFieldTypeToTS maps ONE level of a Go field type (exactly what
// SchemaRef.Fields itself carries — see this file's own package doc
// comment) to a TypeScript type. Anything this codebase's own field types
// don't need to fully resolve — a named struct/enum type Contract never
// describes beyond its bare name — becomes "unknown": inventing a shape
// for it would be a bigger lie than admitting the contract does not know.
func goFieldTypeToTS(goType string) string {
	switch {
	case strings.HasPrefix(goType, "*"):
		return goFieldTypeToTS(goType[1:]) + " | null"
	case goType == "[]uint8":
		// encoding/json marshals a Go []byte as a base64 string, not an array.
		return "string"
	case strings.HasPrefix(goType, "[]"):
		return goFieldTypeToTS(goType[2:]) + "[]"
	case goType == "map[string]string":
		return "Record<string, string>"
	}

	switch goType {
	case "string", "time.Time":
		return "string"
	case "bool":
		return "boolean"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint16", "uint32", "uint64",
		"float32", "float64", "time.Duration":
		return "number"
	default:
		// A named type this one-level-deep contract does not itself expand
		// (e.g. "kanban.KanbanCardDTO", "definition.Kind") — see this
		// function's own doc comment for why "unknown" and not a guess.
		return "unknown"
	}
}

// goPathToTemplateLiteral turns a registered path like
// "/projects/{projectId}/scope-expansions/{requestId}/withdraw" into the
// TypeScript template-literal expression
// `/projects/${projectId}/scope-expansions/${requestId}/withdraw` — the
// exact same {name} segments the function's own parameters above are named
// from, so a rename on one side cannot silently drift from the other.
func goPathToTemplateLiteral(path string, params [][]string) string {
	if len(params) == 0 {
		return fmt.Sprintf("%q", path)
	}
	lit := tsClientPathParamPattern.ReplaceAllStringFunc(path, func(seg string) string {
		name := tsClientPathParamPattern.FindStringSubmatch(seg)[1]
		return "${" + name + "}"
	})
	return "`" + lit + "`"
}
