// Code generated by internal/delivery/httpapi/apicontract.GenerateTypeScriptClient.
// DO NOT EDIT — regenerate via internal/delivery/httpapi/apicontract's own
// TestGeneratedTypeScriptClient_MatchesGoldenFixture (see that test's doc
// comment for the exact regeneration recipe). A change to this file that
// was not produced by regenerating from the real Contract will be
// overwritten and re-fail that test on the next contract change.
//
// Every SchemaRef the real Contract could not describe beyond its own
// top-level field list (see internal/delivery/httpapi/apicontract's own
// "why a custom JSON contract, not full OpenAPI 3.x" doc comment) becomes
// "unknown" here, never a fabricated shape or "any" — narrowing an
// "unknown" at the call site is the caller's own, explicit decision.

export interface RequestOptions {
  /**
   * The per-start session token from window.__AW_BOOTSTRAP__.token. Required
   * for every mutation (anything but GET/HEAD); ignored for a query. Callers
   * MUST keep this in memory only — never write it to a URL, log, or
   * localStorage/sessionStorage (ADR-016).
   */
  token?: string;
  /**
   * Idempotency key for a mutation (ignored for a query). Omit to have one
   * generated per call; pass one explicitly only to retry the exact same
   * logical attempt rather than mint a new one.
   */
  idempotencyKey?: string;
  /**
   * If-Match for an update-shaped mutation (ignored for a query or a
   * create). The server's ETagFromVersion wraps a prior response's own
   * version field in double quotes, so pass that same version wrapped in
   * double quotes, e.g. version 3 becomes a 3-character string: a double
   * quote, the digit 3, and a closing double quote. Required by any route
   * whose handler calls httpapi.RequireIfMatch; omitting it there fails
   * with ErrIfMatchRequired.
   */
  ifMatch?: string;
  /** Extra raw query-string parameters this contract does not itself type. */
  query?: Record<string, string>;
  signal?: AbortSignal;
}

export interface ApiErrorDetail {
  field: string;
  message: string;
}

export class ApiError extends Error {
  constructor(
    public status: number,
    public code: string,
    message: string,
    public details?: ApiErrorDetail[],
  ) {
    super(message);
  }
}

async function request<TResponse>(
  method: string,
  path: string,
  body: unknown,
  opts: RequestOptions,
): Promise<TResponse> {
  const url = new URL(path, window.location.origin);
  if (opts.query) {
    for (const [key, value] of Object.entries(opts.query)) {
      url.searchParams.set(key, value);
    }
  }

  const headers: Record<string, string> = {};
  const isSafeMethod = method === "GET" || method === "HEAD";
  if (!isSafeMethod) {
    if (opts.token) {
      headers["X-Aw-Session-Token"] = opts.token;
    }
    // Every mutation requires an Idempotency-Key (httpapi.RequireIdempotencyKey
    // on the server side); a fresh one per call is correct here for the same
    // reason the aw CLI's own mutations generate one when --idempotency-key
    // is omitted — a caller that wants to retry the SAME logical attempt
    // (rather than mint a new one) passes its own key back via opts.idempotencyKey.
    headers["Idempotency-Key"] = opts.idempotencyKey ?? crypto.randomUUID();
    if (opts.ifMatch) {
      headers["If-Match"] = opts.ifMatch;
    }
  }
  if (body !== undefined) {
    headers["Content-Type"] = "application/json";
  }

  const res = await fetch(url, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
    signal: opts.signal,
  });

  if (!res.ok) {
    const errBody = await res.json().catch(() => null);
    throw new ApiError(
      res.status,
      errBody?.error?.code ?? "UNKNOWN",
      errBody?.error?.message ?? res.statusText,
      errBody?.error?.details,
    );
  }
  if (res.status === 204) {
    return undefined as TResponse;
  }
  return (await res.json()) as TResponse;
}

export interface AbandonReleaseSetResponse {
  releaseSetId: string;
  projectId: string;
  familyId: string;
  state: string;
  contentHash: string;
  version: number;
}

// POST /projects/{projectId}/release-sets/{releaseSetId}/abandon (scope: PROJECT)
export function abandonReleaseSet(projectId: string, releaseSetId: string, body: unknown, opts: RequestOptions = {}): Promise<AbandonReleaseSetResponse> {
  return request<AbandonReleaseSetResponse>("POST", `/projects/${projectId}/release-sets/${releaseSetId}/abandon`, body, opts);
}

export interface AppendConversationAttachmentRequest {
  workItemId: string;
  attemptId?: string;
  role: string;
  contentType: string;
  sensitivity: string;
}

export interface AppendConversationAttachmentResponse {
  messageId: string;
  projectId: string;
  workItemId: string;
  sequence: number;
  contentArtifactId: string;
}

// POST /projects/{projectId}/work-items/{workItemId}/attachments (scope: PROJECT)
export function appendConversationAttachment(projectId: string, workItemId: string, body: AppendConversationAttachmentRequest, opts: RequestOptions = {}): Promise<AppendConversationAttachmentResponse> {
  return request<AppendConversationAttachmentResponse>("POST", `/projects/${projectId}/work-items/${workItemId}/attachments`, body, opts);
}

export interface AppendMessageRequest {
  attemptId?: string;
  role: string;
  content: string;
  contentType: string;
  sensitivity?: string;
}

export interface AppendMessageResponse {
  messageId: string;
  projectId: string;
  workItemId: string;
  sequence: number;
  contentArtifactId: string;
}

// POST /projects/{projectId}/work-items/{workItemId}/messages (scope: PROJECT)
export function appendMessage(projectId: string, workItemId: string, body: AppendMessageRequest, opts: RequestOptions = {}): Promise<AppendMessageResponse> {
  return request<AppendMessageResponse>("POST", `/projects/${projectId}/work-items/${workItemId}/messages`, body, opts);
}

export interface ApproveScopeExpansionResponse {
  requestId: string;
  familyId: string;
  projectId: string;
  newScopeVersion: number;
  approvedGrants: unknown[];
  provisionedRepositories: unknown[];
}

// POST /projects/{projectId}/scope-expansions/{requestId}/approve (scope: PROJECT)
export function approveScopeExpansion(projectId: string, requestId: string, body: unknown, opts: RequestOptions = {}): Promise<ApproveScopeExpansionResponse> {
  return request<ApproveScopeExpansionResponse>("POST", `/projects/${projectId}/scope-expansions/${requestId}/approve`, body, opts);
}

export interface CancelRunRequest {
  reason: string;
}

export interface CancelRunResponse {
  runId: string;
  state: string;
  alreadyRequested: boolean;
  coordinatorJobId?: string;
  validActions: unknown[];
}

// POST /runs/{runId}/cancel (scope: PROJECT)
export function cancelRun(runId: string, body: CancelRunRequest, opts: RequestOptions = {}): Promise<CancelRunResponse> {
  return request<CancelRunResponse>("POST", `/runs/${runId}/cancel`, body, opts);
}

export interface CancelWorkItemRequest {
  reason: string;
}

export interface CancelWorkItemResponse {
  workItemId: string;
  alreadyRequested: boolean;
  status: string;
}

// POST /work-items/{workItemId}/cancel (scope: PROJECT)
export function cancelWorkItem(workItemId: string, body: CancelWorkItemRequest, opts: RequestOptions = {}): Promise<CancelWorkItemResponse> {
  return request<CancelWorkItemResponse>("POST", `/work-items/${workItemId}/cancel`, body, opts);
}

// POST /components/{id}/pack-assignments (scope: PROJECT)
export function componentPackAssignmentsAssign(id: string, body: unknown, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("POST", `/components/${id}/pack-assignments`, body, opts);
}

// GET /components/{id}/pack-assignments (scope: PROJECT)
export function componentPackAssignmentsList(id: string, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("GET", `/components/${id}/pack-assignments`, undefined, opts);
}

export interface CreateChildWorkItemRequest {
  title: string;
  parentJoinPolicy: string;
  sourceNodeRunId?: string;
  effectiveScope: unknown[];
  contract?: unknown | null;
}

export interface CreateChildWorkItemResponse {
  workItemId: string;
  projectId: string;
  familyId: string;
  parentWorkItemId: string;
  status: string;
  effectiveScope: unknown[];
}

// POST /projects/{projectId}/work-items/{workItemId}/children (scope: PROJECT)
export function createChildWorkItem(projectId: string, workItemId: string, body: CreateChildWorkItemRequest, opts: RequestOptions = {}): Promise<CreateChildWorkItemResponse> {
  return request<CreateChildWorkItemResponse>("POST", `/projects/${projectId}/work-items/${workItemId}/children`, body, opts);
}

export interface CreateDefinitionRequest {
  definitionId: string;
  name: string;
}

export interface CreateDefinitionResponse {
  definitionId: string;
  kind: unknown;
}

// POST /definitions/{kind} (scope: INSTALLATION)
export function createDefinition(kind: string, body: CreateDefinitionRequest, opts: RequestOptions = {}): Promise<CreateDefinitionResponse> {
  return request<CreateDefinitionResponse>("POST", `/definitions/${kind}`, body, opts);
}

export interface CreateProjectDefinitionRequest {
  definitionId: string;
  name: string;
}

export interface CreateProjectDefinitionResponse {
  definitionId: string;
  kind: unknown;
}

// POST /projects/{projectId}/definitions/{kind} (scope: PROJECT)
export function createProjectDefinition(projectId: string, kind: string, body: CreateProjectDefinitionRequest, opts: RequestOptions = {}): Promise<CreateProjectDefinitionResponse> {
  return request<CreateProjectDefinitionResponse>("POST", `/projects/${projectId}/definitions/${kind}`, body, opts);
}

export interface CreateReleaseSetRequest {
  repositories: unknown[];
}

export interface CreateReleaseSetResponse {
  releaseSetId: string;
  projectId: string;
  familyId: string;
  state: string;
  contentHash: string;
  version: number;
}

// POST /projects/{projectId}/task-families/{familyId}/release-sets (scope: PROJECT)
export function createReleaseSet(projectId: string, familyId: string, body: CreateReleaseSetRequest, opts: RequestOptions = {}): Promise<CreateReleaseSetResponse> {
  return request<CreateReleaseSetResponse>("POST", `/projects/${projectId}/task-families/${familyId}/release-sets`, body, opts);
}

export interface CreateRootWorkItemRequest {
  title: string;
  initialScope: unknown[];
  contract?: unknown | null;
}

export interface CreateRootWorkItemResponse {
  workItemId: string;
  projectId: string;
  familyId: string;
  workspaceSetId: string;
  status: string;
  provisionedRepositories: unknown[];
}

// POST /projects/{projectId}/work-items (scope: PROJECT)
export function createRootWorkItem(projectId: string, body: CreateRootWorkItemRequest, opts: RequestOptions = {}): Promise<CreateRootWorkItemResponse> {
  return request<CreateRootWorkItemResponse>("POST", `/projects/${projectId}/work-items`, body, opts);
}

export interface DiffDefinitionVersionsResponse {
  a: unknown;
  b: unknown;
  identical: boolean;
  sourceDiff: unknown[];
}

// GET /definitions/versions/diff (scope: INSTALLATION)
export function diffDefinitionVersions(opts: RequestOptions = {}): Promise<DiffDefinitionVersionsResponse> {
  return request<DiffDefinitionVersionsResponse>("GET", "/definitions/versions/diff", undefined, opts);
}

export interface DiffProjectDefinitionVersionsResponse {
  a: unknown;
  b: unknown;
  identical: boolean;
  sourceDiff: unknown[];
}

// GET /projects/{projectId}/definitions/versions/diff (scope: PROJECT)
export function diffProjectDefinitionVersions(projectId: string, opts: RequestOptions = {}): Promise<DiffProjectDefinitionVersionsResponse> {
  return request<DiffProjectDefinitionVersionsResponse>("GET", `/projects/${projectId}/definitions/versions/diff`, undefined, opts);
}

export interface DoctorResponse {
  status: string;
  checks: unknown[];
  restartRequired: boolean;
  links: Record<string, string>;
}

// GET /doctor (scope: INSTALLATION)
export function doctor(opts: RequestOptions = {}): Promise<DoctorResponse> {
  return request<DoctorResponse>("GET", "/doctor", undefined, opts);
}

export interface GetAdapterBuildResponse {
  id: string;
  providerKey: string;
  executablePath: string;
  executableContentHash: string;
  protocolVersion: string;
  capabilityManifestHash: string;
  os: string;
  toolchain: string;
  configIdentity: string;
  capabilityManifest: unknown;
  registeredBy: string;
  registeredAt: string;
}

// GET /adapter-builds/{id} (scope: INSTALLATION)
export function getAdapterBuild(id: string, opts: RequestOptions = {}): Promise<GetAdapterBuildResponse> {
  return request<GetAdapterBuildResponse>("GET", `/adapter-builds/${id}`, undefined, opts);
}

// GET /projects/{projectId}/work-items/{workItemId}/evidence/{evidenceId}/artifacts/{artifactId}/content (scope: PROJECT)
export function getArtifactContent(projectId: string, workItemId: string, evidenceId: string, artifactId: string, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("GET", `/projects/${projectId}/work-items/${workItemId}/evidence/${evidenceId}/artifacts/${artifactId}/content`, undefined, opts);
}

export interface GetContextSnapshotResponse {
  snapshotId: string;
  projectId: string;
  workItemId: string;
  attemptId: string;
  messageRefs?: unknown[];
  resourceRefs?: unknown[];
  evidenceRefs?: unknown[];
  revisions?: unknown[];
  revisionSetHash: string;
  manifestHash: string;
  createdAt: string;
}

// GET /projects/{projectId}/work-items/{workItemId}/context-snapshots/{snapshotId} (scope: PROJECT)
export function getContextSnapshot(projectId: string, workItemId: string, snapshotId: string, opts: RequestOptions = {}): Promise<GetContextSnapshotResponse> {
  return request<GetContextSnapshotResponse>("GET", `/projects/${projectId}/work-items/${workItemId}/context-snapshots/${snapshotId}`, undefined, opts);
}

export interface GetDefinitionResponse {
  id: string;
  kind: unknown;
  scope: unknown;
  name: string;
  status: unknown;
  version: number;
}

// GET /definitions/{kind}/{id} (scope: INSTALLATION)
export function getDefinition(kind: string, id: string, opts: RequestOptions = {}): Promise<GetDefinitionResponse> {
  return request<GetDefinitionResponse>("GET", `/definitions/${kind}/${id}`, undefined, opts);
}

export interface GetDefinitionVersionResponse {
  id: string;
  definitionId: string;
  kind: unknown;
  versionNumber: number;
  schemaVersion: number;
  canonicalSource: string;
  sourceHash: string;
  compiledSnapshot: string;
  compiledHash: string;
  dependencies: unknown;
  publishedBy: string;
  publishedAt: string;
}

// GET /definitions/versions/{versionId} (scope: INSTALLATION)
export function getDefinitionVersion(versionId: string, opts: RequestOptions = {}): Promise<GetDefinitionVersionResponse> {
  return request<GetDefinitionVersionResponse>("GET", `/definitions/versions/${versionId}`, undefined, opts);
}

export interface GetEvidenceResponse {
  evidenceId: string;
  projectId: string;
  workItemId: string;
  runId: string;
  nodeRunId: string;
  attemptId: string;
  kind: string;
  verdict: string;
  artifactReferences?: string[];
  revisions?: unknown[];
  revisionSetHash: string;
  policyVersion: string;
  createdAt: string;
}

// GET /projects/{projectId}/work-items/{workItemId}/evidence/{evidenceId} (scope: PROJECT)
export function getEvidence(projectId: string, workItemId: string, evidenceId: string, opts: RequestOptions = {}): Promise<GetEvidenceResponse> {
  return request<GetEvidenceResponse>("GET", `/projects/${projectId}/work-items/${workItemId}/evidence/${evidenceId}`, undefined, opts);
}

export interface GetMessageContextSnapshotResponse {
  snapshotId: string;
  projectId: string;
  workItemId: string;
  attemptId: string;
  messageRefs?: unknown[];
  resourceRefs?: unknown[];
  evidenceRefs?: unknown[];
  revisions?: unknown[];
  revisionSetHash: string;
  manifestHash: string;
  createdAt: string;
}

// GET /projects/{projectId}/work-items/{workItemId}/messages/{messageId}/context-snapshot (scope: PROJECT)
export function getMessageContextSnapshot(projectId: string, workItemId: string, messageId: string, opts: RequestOptions = {}): Promise<GetMessageContextSnapshotResponse> {
  return request<GetMessageContextSnapshotResponse>("GET", `/projects/${projectId}/work-items/${workItemId}/messages/${messageId}/context-snapshot`, undefined, opts);
}

export interface GetProjectDefinitionResponse {
  id: string;
  kind: unknown;
  scope: unknown;
  name: string;
  status: unknown;
  version: number;
}

// GET /projects/{projectId}/definitions/{kind}/{id} (scope: PROJECT)
export function getProjectDefinition(projectId: string, kind: string, id: string, opts: RequestOptions = {}): Promise<GetProjectDefinitionResponse> {
  return request<GetProjectDefinitionResponse>("GET", `/projects/${projectId}/definitions/${kind}/${id}`, undefined, opts);
}

export interface GetProjectDefinitionVersionResponse {
  id: string;
  definitionId: string;
  kind: unknown;
  versionNumber: number;
  schemaVersion: number;
  canonicalSource: string;
  sourceHash: string;
  compiledSnapshot: string;
  compiledHash: string;
  dependencies: unknown;
  publishedBy: string;
  publishedAt: string;
}

// GET /projects/{projectId}/definitions/versions/{versionId} (scope: PROJECT)
export function getProjectDefinitionVersion(projectId: string, versionId: string, opts: RequestOptions = {}): Promise<GetProjectDefinitionVersionResponse> {
  return request<GetProjectDefinitionVersionResponse>("GET", `/projects/${projectId}/definitions/versions/${versionId}`, undefined, opts);
}

export interface GetProjectionRebuildOperationStatusResponse {
  operationId: string;
  projectId: string;
  projectionName: string;
  phase: string;
  w0?: number | null;
  shadowGeneration?: number | null;
  shadowCursor?: number | null;
  cutoverCursor?: number | null;
  errorCode?: string;
  errorMessage?: string;
  jobId: string;
  requestedAt: string;
  updatedAt: string;
  version: number;
}

// GET /projects/{id}/projection/rebuild-operations/{operationId} (scope: PROJECT)
export function getProjectionRebuildOperationStatus(id: string, operationId: string, opts: RequestOptions = {}): Promise<GetProjectionRebuildOperationStatusResponse> {
  return request<GetProjectionRebuildOperationStatusResponse>("GET", `/projects/${id}/projection/rebuild-operations/${operationId}`, undefined, opts);
}

export interface GetProjectionStatusResponse {
  projectId: string;
  projectionName: string;
  freshness: unknown;
}

// GET /projects/{id}/projection (scope: PROJECT)
export function getProjectionStatus(id: string, opts: RequestOptions = {}): Promise<GetProjectionStatusResponse> {
  return request<GetProjectionStatusResponse>("GET", `/projects/${id}/projection`, undefined, opts);
}

export interface GetReleaseSetResponse {
  releaseSetId: string;
  projectId: string;
  familyId: string;
  state: string;
  contentHash: string;
  version: number;
  entries: unknown[];
}

// GET /projects/{projectId}/release-sets/{releaseSetId} (scope: PROJECT)
export function getReleaseSet(projectId: string, releaseSetId: string, opts: RequestOptions = {}): Promise<GetReleaseSetResponse> {
  return request<GetReleaseSetResponse>("GET", `/projects/${projectId}/release-sets/${releaseSetId}`, undefined, opts);
}

export interface GetReleaseSetLocalCommitStatusResponse {
  releaseSetLocalCommitId: string;
  projectId: string;
  releaseSetId: string;
  repositoryWorkspaceId: string;
  repositoryId: string;
  state: string;
  failureReason?: string;
  parentVcsObjectId?: string;
  resultVcsObjectId?: string;
  jobId: string;
  createdAt: string;
  completedAt?: string | null;
  version: number;
}

// GET /projects/{projectId}/release-sets/{releaseSetId}/local-commits/{localCommitId} (scope: PROJECT)
export function getReleaseSetLocalCommitStatus(projectId: string, releaseSetId: string, localCommitId: string, opts: RequestOptions = {}): Promise<GetReleaseSetLocalCommitStatusResponse> {
  return request<GetReleaseSetLocalCommitStatusResponse>("GET", `/projects/${projectId}/release-sets/${releaseSetId}/local-commits/${localCommitId}`, undefined, opts);
}

export interface GetRepositoryWorkspaceStateResponse {
  repositoryWorkspaceId: string;
  workspaceSetId: string;
  repositoryId: string;
  generation: number;
  state: string;
  version: number;
  branchRef?: string;
  currentRevision?: string;
  lastProvisionErrorCode?: string | null;
  hasActiveWriteLease: boolean;
  validActions: unknown[];
}

// GET /projects/{projectId}/repository-workspaces/{repositoryWorkspaceId} (scope: PROJECT)
export function getRepositoryWorkspaceState(projectId: string, repositoryWorkspaceId: string, opts: RequestOptions = {}): Promise<GetRepositoryWorkspaceStateResponse> {
  return request<GetRepositoryWorkspaceStateResponse>("GET", `/projects/${projectId}/repository-workspaces/${repositoryWorkspaceId}`, undefined, opts);
}

export interface GetRunDetailResponse {
  runId: string;
  projectId: string;
  workItemId: string;
  familyId: string;
  state: string;
  version: number;
  scopeVersion: number;
  workflowVersionId: string;
  workflowVersionHash: string;
  startedAt?: string | null;
  finishedAt?: string | null;
  cancelling: boolean;
  manifest: unknown;
  amendments?: unknown[];
  nodeRunCount: number;
  executionAttemptCount: number;
  approvalRequests?: unknown[];
  waitRegistrations?: unknown[];
}

// GET /runs/{id} (scope: PROJECT)
export function getRunDetail(id: string, opts: RequestOptions = {}): Promise<GetRunDetailResponse> {
  return request<GetRunDetailResponse>("GET", `/runs/${id}`, undefined, opts);
}

export interface GetRunDiagnosticsResponse {
  runId: string;
  projectId: string;
  workItemId: string;
  workItemStatus: string;
  runState: string;
  blockers: unknown[];
  orphanedAttempts: unknown[];
  orphanedAttemptsTruncated: boolean;
  providers: unknown[];
  isolation: unknown[];
  repositoryWorkspaces: unknown[];
  validActions: unknown[];
}

// GET /projects/{projectId}/runs/{runId}/diagnostics (scope: PROJECT)
export function getRunDiagnostics(projectId: string, runId: string, opts: RequestOptions = {}): Promise<GetRunDiagnosticsResponse> {
  return request<GetRunDiagnosticsResponse>("GET", `/projects/${projectId}/runs/${runId}/diagnostics`, undefined, opts);
}

export interface GetRunGraphResponse {
  runId: string;
  manifestRevision: number;
  nodes: unknown[];
  possibleEdges: unknown[];
  takenEdges?: unknown[];
  activations: unknown[];
  branchTokens?: unknown[];
  freshness: unknown;
  nextCursor?: string;
}

// GET /runs/{id}/graph (scope: PROJECT)
export function getRunGraph(id: string, opts: RequestOptions = {}): Promise<GetRunGraphResponse> {
  return request<GetRunGraphResponse>("GET", `/runs/${id}/graph`, undefined, opts);
}

export interface GetRunTimelineResponse {
  runId: string;
  entries: unknown[];
  freshness: unknown;
  nextCursor?: string;
}

// GET /runs/{id}/timeline (scope: PROJECT)
export function getRunTimeline(id: string, opts: RequestOptions = {}): Promise<GetRunTimelineResponse> {
  return request<GetRunTimelineResponse>("GET", `/runs/${id}/timeline`, undefined, opts);
}

export interface GetSafeSettingsResponse {
  desired: unknown;
  version: number;
  updatedAt: string;
  updatedBy: string;
  restartRequired: boolean;
  effective: unknown;
}

// GET /settings/safe (scope: INSTALLATION)
export function getSafeSettings(opts: RequestOptions = {}): Promise<GetSafeSettingsResponse> {
  return request<GetSafeSettingsResponse>("GET", "/settings/safe", undefined, opts);
}

export interface GetScopeExpansionRequestResponse {
  requestId: string;
  familyId: string;
  projectId: string;
  requestedGrants: unknown[];
  reason: string;
  referencedWorkItemId?: string;
  status: string;
  requestedBy: string;
  requestedAt: string;
  decidedBy?: string;
  decidedAt?: string | null;
  decisionNote?: string;
  approvedScopeVersion?: number | null;
  version: number;
}

// GET /projects/{projectId}/scope-expansions/{requestId} (scope: PROJECT)
export function getScopeExpansionRequest(projectId: string, requestId: string, opts: RequestOptions = {}): Promise<GetScopeExpansionRequestResponse> {
  return request<GetScopeExpansionRequestResponse>("GET", `/projects/${projectId}/scope-expansions/${requestId}`, undefined, opts);
}

export interface GetTaskFamilyResponse {
  familyId: string;
  projectId: string;
  rootWorkItemId: string;
  scopeVersion: number;
  status: string;
  version: number;
}

// GET /projects/{projectId}/task-families/{familyId} (scope: PROJECT)
export function getTaskFamily(projectId: string, familyId: string, opts: RequestOptions = {}): Promise<GetTaskFamilyResponse> {
  return request<GetTaskFamilyResponse>("GET", `/projects/${projectId}/task-families/${familyId}`, undefined, opts);
}

export interface GetWorkItemResponse {
  workItemId: string;
  projectId: string;
  familyId: string;
  kind: string;
  parentWorkItemId?: string;
  title: string;
  status: string;
  version: number;
  parentJoinPolicy?: string;
  sourceNodeRunId?: string;
  workflowVersionId?: string;
  contract?: unknown | null;
}

// GET /projects/{projectId}/work-items/{workItemId} (scope: PROJECT)
export function getWorkItem(projectId: string, workItemId: string, opts: RequestOptions = {}): Promise<GetWorkItemResponse> {
  return request<GetWorkItemResponse>("GET", `/projects/${projectId}/work-items/${workItemId}`, undefined, opts);
}

export interface GetWorkItemProjectedDetailResponse {
  card: unknown;
  readiness: unknown;
  freshness: unknown;
  validActions: unknown[];
}

// GET /work-items/{workItemId}/detail (scope: PROJECT)
export function getWorkItemProjectedDetail(workItemId: string, opts: RequestOptions = {}): Promise<GetWorkItemProjectedDetailResponse> {
  return request<GetWorkItemProjectedDetailResponse>("GET", `/work-items/${workItemId}/detail`, undefined, opts);
}

export interface GetWorkItemReadinessResponse {
  workItemId: string;
  status: string;
  version: number;
  ready: boolean;
  problems?: string[];
}

// GET /projects/{projectId}/work-items/{workItemId}/readiness (scope: PROJECT)
export function getWorkItemReadiness(projectId: string, workItemId: string, opts: RequestOptions = {}): Promise<GetWorkItemReadinessResponse> {
  return request<GetWorkItemReadinessResponse>("GET", `/projects/${projectId}/work-items/${workItemId}/readiness`, undefined, opts);
}

export interface GetWorkspaceDiffResponse {
  baseRevision: unknown;
  resultRevision: unknown;
  files: unknown[];
  patch: string;
  byteLimit: number;
  fileLimit: number;
  filesTruncated: boolean;
  patchTruncated: boolean;
}

// GET /projects/{projectId}/repository-workspaces/{repositoryWorkspaceId}/diff (scope: PROJECT)
export function getWorkspaceDiff(projectId: string, repositoryWorkspaceId: string, opts: RequestOptions = {}): Promise<GetWorkspaceDiffResponse> {
  return request<GetWorkspaceDiffResponse>("GET", `/projects/${projectId}/repository-workspaces/${repositoryWorkspaceId}/diff`, undefined, opts);
}

export interface GetWorkspaceRepositoryLogResponse {
  anchor: unknown;
  entries: unknown[];
  nextCursor?: string;
  limit: number;
  byteLimit: number;
  truncated: boolean;
}

// GET /projects/{projectId}/repository-workspaces/{repositoryWorkspaceId}/repository-log (scope: PROJECT)
export function getWorkspaceRepositoryLog(projectId: string, repositoryWorkspaceId: string, opts: RequestOptions = {}): Promise<GetWorkspaceRepositoryLogResponse> {
  return request<GetWorkspaceRepositoryLogResponse>("GET", `/projects/${projectId}/repository-workspaces/${repositoryWorkspaceId}/repository-log`, undefined, opts);
}

export interface GetWorkspaceSetStateResponse {
  workspaceSetId: string;
  familyId: string;
  projectId: string;
  state: string;
  version: number;
  hasBaseRevisionSet: boolean;
  repositoryWorkspaces: unknown[];
  validActions: unknown[];
}

// GET /projects/{projectId}/workspace-sets/{familyId} (scope: PROJECT)
export function getWorkspaceSetState(projectId: string, familyId: string, opts: RequestOptions = {}): Promise<GetWorkspaceSetStateResponse> {
  return request<GetWorkspaceSetStateResponse>("GET", `/projects/${projectId}/workspace-sets/${familyId}`, undefined, opts);
}

// GET /projects/{projectId}/repository-workspaces/{repositoryWorkspaceId}/source (scope: PROJECT)
export function getWorkspaceSource(projectId: string, repositoryWorkspaceId: string, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("GET", `/projects/${projectId}/repository-workspaces/${repositoryWorkspaceId}/source`, undefined, opts);
}

// GET /health/live (scope: INSTALLATION)
export function healthLive(opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("GET", "/health/live", undefined, opts);
}

// GET /health/ready (scope: INSTALLATION)
export function healthReady(opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("GET", "/health/ready", undefined, opts);
}

export interface ListAdapterBuildsResponse {
  builds: unknown[];
}

// GET /adapter-builds (scope: INSTALLATION)
export function listAdapterBuilds(opts: RequestOptions = {}): Promise<ListAdapterBuildsResponse> {
  return request<ListAdapterBuildsResponse>("GET", "/adapter-builds", undefined, opts);
}

export interface ListArtifactsResponse {
  items: unknown[];
}

// GET /projects/{projectId}/work-items/{workItemId}/evidence/{evidenceId}/artifacts (scope: PROJECT)
export function listArtifacts(projectId: string, workItemId: string, evidenceId: string, opts: RequestOptions = {}): Promise<ListArtifactsResponse> {
  return request<ListArtifactsResponse>("GET", `/projects/${projectId}/work-items/${workItemId}/evidence/${evidenceId}/artifacts`, undefined, opts);
}

export interface ListChildWorkItemsResponse {
  items: unknown[];
}

// GET /projects/{projectId}/work-items/{workItemId}/children (scope: PROJECT)
export function listChildWorkItems(projectId: string, workItemId: string, opts: RequestOptions = {}): Promise<ListChildWorkItemsResponse> {
  return request<ListChildWorkItemsResponse>("GET", `/projects/${projectId}/work-items/${workItemId}/children`, undefined, opts);
}

export interface ListDefinitionVersionsResponse {
  items: unknown[];
}

// GET /definitions/{kind}/{id}/versions (scope: INSTALLATION)
export function listDefinitionVersions(kind: string, id: string, opts: RequestOptions = {}): Promise<ListDefinitionVersionsResponse> {
  return request<ListDefinitionVersionsResponse>("GET", `/definitions/${kind}/${id}/versions`, undefined, opts);
}

export interface ListEvidenceResponse {
  items: unknown[];
}

// GET /projects/{projectId}/work-items/{workItemId}/evidence (scope: PROJECT)
export function listEvidence(projectId: string, workItemId: string, opts: RequestOptions = {}): Promise<ListEvidenceResponse> {
  return request<ListEvidenceResponse>("GET", `/projects/${projectId}/work-items/${workItemId}/evidence`, undefined, opts);
}

export interface ListMessagesResponse {
  items: unknown[];
  nextCursor?: string;
}

// GET /projects/{projectId}/work-items/{workItemId}/messages (scope: PROJECT)
export function listMessages(projectId: string, workItemId: string, opts: RequestOptions = {}): Promise<ListMessagesResponse> {
  return request<ListMessagesResponse>("GET", `/projects/${projectId}/work-items/${workItemId}/messages`, undefined, opts);
}

export interface ListProjectDefinitionVersionsResponse {
  items: unknown[];
}

// GET /projects/{projectId}/definitions/{kind}/{id}/versions (scope: PROJECT)
export function listProjectDefinitionVersions(projectId: string, kind: string, id: string, opts: RequestOptions = {}): Promise<ListProjectDefinitionVersionsResponse> {
  return request<ListProjectDefinitionVersionsResponse>("GET", `/projects/${projectId}/definitions/${kind}/${id}/versions`, undefined, opts);
}

export interface ListReleaseSetsForFamilyResponse {
  items: unknown[];
}

// GET /projects/{projectId}/task-families/{familyId}/release-sets (scope: PROJECT)
export function listReleaseSetsForFamily(projectId: string, familyId: string, opts: RequestOptions = {}): Promise<ListReleaseSetsForFamilyResponse> {
  return request<ListReleaseSetsForFamilyResponse>("GET", `/projects/${projectId}/task-families/${familyId}/release-sets`, undefined, opts);
}

export interface ListWorkItemKanbanResponse {
  items: unknown[];
  nextCursor?: string;
  freshness: unknown;
}

// GET /projects/{projectId}/work-items/kanban (scope: PROJECT)
export function listWorkItemKanban(projectId: string, opts: RequestOptions = {}): Promise<ListWorkItemKanbanResponse> {
  return request<ListWorkItemKanbanResponse>("GET", `/projects/${projectId}/work-items/kanban`, undefined, opts);
}

export interface ListWorkItemsResponse {
  items: unknown[];
}

// GET /projects/{projectId}/work-items (scope: PROJECT)
export function listWorkItems(projectId: string, opts: RequestOptions = {}): Promise<ListWorkItemsResponse> {
  return request<ListWorkItemsResponse>("GET", `/projects/${projectId}/work-items`, undefined, opts);
}

export interface MarkWorkItemReadyResponse {
  workItemId: string;
  projectId: string;
  familyId: string;
  status: string;
  version: number;
}

// POST /work-items/{workItemId}/mark-ready (scope: PROJECT)
export function markWorkItemReady(workItemId: string, body: unknown, opts: RequestOptions = {}): Promise<MarkWorkItemReadyResponse> {
  return request<MarkWorkItemReadyResponse>("POST", `/work-items/${workItemId}/mark-ready`, body, opts);
}

export interface ProbeAdapterBuildRequest {
  providerKey: string;
  executablePath: string;
  protocolVersion: string;
  capabilityManifest: unknown;
  os: string;
  toolchain: string;
  configIdentity: string;
}

export interface ProbeAdapterBuildResponse {
  tuple: unknown;
  nonce: string;
  expiresAt: string;
  signature: string;
}

// POST /adapter-builds/probe (scope: INSTALLATION)
export function probeAdapterBuild(body: ProbeAdapterBuildRequest, opts: RequestOptions = {}): Promise<ProbeAdapterBuildResponse> {
  return request<ProbeAdapterBuildResponse>("POST", "/adapter-builds/probe", body, opts);
}

// GET /projects/{id}/components (scope: PROJECT)
export function projectComponentsList(id: string, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("GET", `/projects/${id}/components`, undefined, opts);
}

// GET /projects/{id}/repositories (scope: PROJECT)
export function projectRepositoriesList(id: string, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("GET", `/projects/${id}/repositories`, undefined, opts);
}

// POST /projects/{id}/repositories (scope: PROJECT)
export function projectRepositoriesRegister(id: string, body: unknown, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("POST", `/projects/${id}/repositories`, body, opts);
}

// POST /projects (scope: INSTALLATION)
export function projectsCreate(body: unknown, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("POST", "/projects", body, opts);
}

// GET /projects/{id} (scope: PROJECT)
export function projectsGet(id: string, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("GET", `/projects/${id}`, undefined, opts);
}

// GET /projects (scope: INSTALLATION)
export function projectsList(opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("GET", "/projects", undefined, opts);
}

export interface PublishDefinitionVersionRequest {
  content: string;
  format?: string;
  schemaVersion?: number;
  dependencies?: unknown[];
}

export interface PublishDefinitionVersionResponse {
  id: string;
  definitionId: string;
  kind: unknown;
  versionNumber: number;
  schemaVersion: number;
  canonicalSource: string;
  sourceHash: string;
  compiledSnapshot: string;
  compiledHash: string;
  dependencies: unknown;
  publishedBy: string;
  publishedAt: string;
}

// POST /definitions/{kind}/{id}/publish (scope: INSTALLATION)
export function publishDefinitionVersion(kind: string, id: string, body: PublishDefinitionVersionRequest, opts: RequestOptions = {}): Promise<PublishDefinitionVersionResponse> {
  return request<PublishDefinitionVersionResponse>("POST", `/definitions/${kind}/${id}/publish`, body, opts);
}

export interface PublishProjectDefinitionVersionRequest {
  content: string;
  format?: string;
  schemaVersion?: number;
  dependencies?: unknown[];
}

export interface PublishProjectDefinitionVersionResponse {
  id: string;
  definitionId: string;
  kind: unknown;
  versionNumber: number;
  schemaVersion: number;
  canonicalSource: string;
  sourceHash: string;
  compiledSnapshot: string;
  compiledHash: string;
  dependencies: unknown;
  publishedBy: string;
  publishedAt: string;
}

// POST /projects/{projectId}/definitions/{kind}/{id}/publish (scope: PROJECT)
export function publishProjectDefinitionVersion(projectId: string, kind: string, id: string, body: PublishProjectDefinitionVersionRequest, opts: RequestOptions = {}): Promise<PublishProjectDefinitionVersionResponse> {
  return request<PublishProjectDefinitionVersionResponse>("POST", `/projects/${projectId}/definitions/${kind}/${id}/publish`, body, opts);
}

export interface RegisterAdapterBuildRequest {
  token: unknown;
  capabilityManifest: unknown;
}

export interface RegisterAdapterBuildResponse {
  build: unknown;
  alreadyExisted: boolean;
}

// POST /adapter-builds (scope: INSTALLATION)
export function registerAdapterBuild(body: RegisterAdapterBuildRequest, opts: RequestOptions = {}): Promise<RegisterAdapterBuildResponse> {
  return request<RegisterAdapterBuildResponse>("POST", "/adapter-builds", body, opts);
}

export interface RejectScopeExpansionRequest {
  decisionNote: string;
}

export interface RejectScopeExpansionResponse {
  requestId: string;
  status: string;
}

// POST /projects/{projectId}/scope-expansions/{requestId}/reject (scope: PROJECT)
export function rejectScopeExpansion(projectId: string, requestId: string, body: RejectScopeExpansionRequest, opts: RequestOptions = {}): Promise<RejectScopeExpansionResponse> {
  return request<RejectScopeExpansionResponse>("POST", `/projects/${projectId}/scope-expansions/${requestId}/reject`, body, opts);
}

// GET /repositories/{id} (scope: PROJECT)
export function repositoriesGet(id: string, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("GET", `/repositories/${id}`, undefined, opts);
}

// GET /repositories/{id}/onboarding (scope: PROJECT)
export function repositoriesOnboarding(id: string, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("GET", `/repositories/${id}/onboarding`, undefined, opts);
}

// POST /repositories/{id}/retry-probe (scope: PROJECT)
export function repositoriesRetryProbe(id: string, body: unknown, opts: RequestOptions = {}): Promise<unknown> {
  return request<unknown>("POST", `/repositories/${id}/retry-probe`, body, opts);
}

export interface RequestProjectionRebuildRequest {
  projectionName: string;
}

export interface RequestProjectionRebuildResponse {
  operationId: string;
  projectId: string;
  projectionName: string;
  phase: string;
  jobId: string;
}

// POST /projects/{id}/projection/rebuild (scope: PROJECT)
export function requestProjectionRebuild(id: string, body: RequestProjectionRebuildRequest, opts: RequestOptions = {}): Promise<RequestProjectionRebuildResponse> {
  return request<RequestProjectionRebuildResponse>("POST", `/projects/${id}/projection/rebuild`, body, opts);
}

export interface RequestReleaseSetLocalCommitRequest {
  expectedReleaseSetVersion: number;
  repositoryWorkspaceId: string;
  expectedWorkspaceVersion: number;
  message: string;
  authorName: string;
  authorEmail: string;
}

export interface RequestReleaseSetLocalCommitResponse {
  releaseSetLocalCommitId: string;
  releaseSetId: string;
  repositoryWorkspaceId: string;
  state: string;
  jobId: string;
  marker: string;
}

// POST /projects/{projectId}/release-sets/{releaseSetId}/local-commits (scope: PROJECT)
export function requestReleaseSetLocalCommit(projectId: string, releaseSetId: string, body: RequestReleaseSetLocalCommitRequest, opts: RequestOptions = {}): Promise<RequestReleaseSetLocalCommitResponse> {
  return request<RequestReleaseSetLocalCommitResponse>("POST", `/projects/${projectId}/release-sets/${releaseSetId}/local-commits`, body, opts);
}

export interface RequestScopeExpansionRequest {
  requestedGrants: unknown[];
  reason: string;
  referencedWorkItemId?: string;
}

export interface RequestScopeExpansionResponse {
  requestId: string;
  familyId: string;
  projectId: string;
  status: string;
}

// POST /projects/{projectId}/task-families/{familyId}/scope-expansions (scope: PROJECT)
export function requestScopeExpansion(projectId: string, familyId: string, body: RequestScopeExpansionRequest, opts: RequestOptions = {}): Promise<RequestScopeExpansionResponse> {
  return request<RequestScopeExpansionResponse>("POST", `/projects/${projectId}/task-families/${familyId}/scope-expansions`, body, opts);
}

export interface RequestWorkspaceReconciliationResponse {
  repositoryWorkspaceId: string;
  projectId: string;
  state: string;
  reconciliationJobId: string;
}

// POST /projects/{projectId}/repository-workspaces/{repositoryWorkspaceId}/reconcile (scope: PROJECT)
export function requestWorkspaceReconciliation(projectId: string, repositoryWorkspaceId: string, body: unknown, opts: RequestOptions = {}): Promise<RequestWorkspaceReconciliationResponse> {
  return request<RequestWorkspaceReconciliationResponse>("POST", `/projects/${projectId}/repository-workspaces/${repositoryWorkspaceId}/reconcile`, body, opts);
}

export interface RequestWorkspaceSetReleaseResponse {
  workspaceSetId: string;
  familyId: string;
  projectId: string;
  state: string;
  releaseJobId: string;
}

// POST /projects/{projectId}/workspace-sets/{familyId}/release (scope: PROJECT)
export function requestWorkspaceSetRelease(projectId: string, familyId: string, body: unknown, opts: RequestOptions = {}): Promise<RequestWorkspaceSetReleaseResponse> {
  return request<RequestWorkspaceSetReleaseResponse>("POST", `/projects/${projectId}/workspace-sets/${familyId}/release`, body, opts);
}

export interface ResolveApprovalRequest {
  outcome: string;
  reason?: string;
}

export interface ResolveApprovalResponse {
  ResolveApprovalResult: unknown;
  validActions: unknown[];
}

// POST /runs/{runId}/approval-requests/{approvalRequestId}/resolve (scope: PROJECT)
export function resolveApproval(runId: string, approvalRequestId: string, body: ResolveApprovalRequest, opts: RequestOptions = {}): Promise<ResolveApprovalResponse> {
  return request<ResolveApprovalResponse>("POST", `/runs/${runId}/approval-requests/${approvalRequestId}/resolve`, body, opts);
}

export interface ResolveWorkItemBlockerRequest {
  mode: string;
  reason: string;
  policyGrantRef?: string;
}

export interface ResolveWorkItemBlockerResponse {
  blockerId: string;
  alreadyResolved: boolean;
  state: string;
  workItemUnblocked: boolean;
  workItemStatus: string;
}

// POST /work-item-blockers/{blockerId}/resolve (scope: PROJECT)
export function resolveWorkItemBlocker(blockerId: string, body: ResolveWorkItemBlockerRequest, opts: RequestOptions = {}): Promise<ResolveWorkItemBlockerResponse> {
  return request<ResolveWorkItemBlockerResponse>("POST", `/work-item-blockers/${blockerId}/resolve`, body, opts);
}

export interface RetryBlockedActivationRequest {
  reason: string;
}

export interface RetryBlockedActivationResponse {
  nodeRunId: string;
  alreadyRetried: boolean;
  retried: boolean;
  reactivatedNodeRunId?: string;
  failureReason?: string;
  failureDetail?: string;
}

// POST /node-runs/{nodeRunId}/retry-blocked-activation (scope: PROJECT)
export function retryBlockedActivation(nodeRunId: string, body: RetryBlockedActivationRequest, opts: RequestOptions = {}): Promise<RetryBlockedActivationResponse> {
  return request<RetryBlockedActivationResponse>("POST", `/node-runs/${nodeRunId}/retry-blocked-activation`, body, opts);
}

export interface SealReleaseSetResponse {
  releaseSetId: string;
  projectId: string;
  familyId: string;
  state: string;
  contentHash: string;
  version: number;
}

// POST /projects/{projectId}/release-sets/{releaseSetId}/seal (scope: PROJECT)
export function sealReleaseSet(projectId: string, releaseSetId: string, body: unknown, opts: RequestOptions = {}): Promise<SealReleaseSetResponse> {
  return request<SealReleaseSetResponse>("POST", `/projects/${projectId}/release-sets/${releaseSetId}/seal`, body, opts);
}

export interface StartWorkflowRunRequest {
  workflowVersionId: string;
}

export interface StartWorkflowRunResponse {
  StartWorkflowRunResult: unknown;
  validActions: unknown[];
}

// POST /work-items/{workItemId}/runs (scope: PROJECT)
export function startWorkflowRun(workItemId: string, body: StartWorkflowRunRequest, opts: RequestOptions = {}): Promise<StartWorkflowRunResponse> {
  return request<StartWorkflowRunResponse>("POST", `/work-items/${workItemId}/runs`, body, opts);
}

export interface SubmitWaitSignalRequest {
  signalKey: string;
  payload?: unknown;
}

export interface SubmitWaitSignalResponse {
  SignalWaitResult: unknown;
  validActions: unknown[];
}

// POST /runs/{runId}/wait-registrations/{waitRegistrationId}/signal (scope: PROJECT)
export function submitWaitSignal(runId: string, waitRegistrationId: string, body: SubmitWaitSignalRequest, opts: RequestOptions = {}): Promise<SubmitWaitSignalResponse> {
  return request<SubmitWaitSignalResponse>("POST", `/runs/${runId}/wait-registrations/${waitRegistrationId}/signal`, body, opts);
}

export interface UpdateSafeSettingsRequest {
  ManagedWorkspaceRoot: string;
  ManagedArtifactRoot: string;
  EvidenceRetention: number;
  ProcessOutputLimit: number;
  ProviderExecutablePath: string;
  ProviderDefaultModel: string;
  ProviderCredentialRef: string;
}

export interface UpdateSafeSettingsResponse {
  desired: unknown;
  version: number;
  updatedAt: string;
  updatedBy: string;
  restartRequired: boolean;
  effective: unknown;
}

// PUT /settings/safe (scope: INSTALLATION)
export function updateSafeSettings(body: UpdateSafeSettingsRequest, opts: RequestOptions = {}): Promise<UpdateSafeSettingsResponse> {
  return request<UpdateSafeSettingsResponse>("PUT", "/settings/safe", body, opts);
}

export interface ValidateDefinitionDraftRequest {
  content: string;
  format?: string;
  schemaVersion?: number;
  dependencies?: unknown[];
}

export interface ValidateDefinitionDraftResponse {
  id: string;
  definitionId: string;
  kind: unknown;
  versionNumber: number;
  schemaVersion: number;
  canonicalSource: string;
  sourceHash: string;
  compiledSnapshot: string;
  compiledHash: string;
  dependencies: unknown;
  publishedBy: string;
  publishedAt: string;
}

// POST /definitions/{kind}/{id}/validate (scope: INSTALLATION)
export function validateDefinitionDraft(kind: string, id: string, body: ValidateDefinitionDraftRequest, opts: RequestOptions = {}): Promise<ValidateDefinitionDraftResponse> {
  return request<ValidateDefinitionDraftResponse>("POST", `/definitions/${kind}/${id}/validate`, body, opts);
}

export interface ValidateProjectDefinitionDraftRequest {
  content: string;
  format?: string;
  schemaVersion?: number;
  dependencies?: unknown[];
}

export interface ValidateProjectDefinitionDraftResponse {
  id: string;
  definitionId: string;
  kind: unknown;
  versionNumber: number;
  schemaVersion: number;
  canonicalSource: string;
  sourceHash: string;
  compiledSnapshot: string;
  compiledHash: string;
  dependencies: unknown;
  publishedBy: string;
  publishedAt: string;
}

// POST /projects/{projectId}/definitions/{kind}/{id}/validate (scope: PROJECT)
export function validateProjectDefinitionDraft(projectId: string, kind: string, id: string, body: ValidateProjectDefinitionDraftRequest, opts: RequestOptions = {}): Promise<ValidateProjectDefinitionDraftResponse> {
  return request<ValidateProjectDefinitionDraftResponse>("POST", `/projects/${projectId}/definitions/${kind}/${id}/validate`, body, opts);
}

export interface WatchProjectEventsResponse {
  journalPosition: number;
  eventType: string;
  schemaVersion: number;
}

// GET /projects/{id}/events/watch (scope: PROJECT)
export function watchProjectEvents(id: string, opts: RequestOptions = {}): Promise<WatchProjectEventsResponse> {
  return request<WatchProjectEventsResponse>("GET", `/projects/${id}/events/watch`, undefined, opts);
}

export interface WithdrawScopeExpansionResponse {
  requestId: string;
  status: string;
}

// POST /projects/{projectId}/scope-expansions/{requestId}/withdraw (scope: PROJECT)
export function withdrawScopeExpansion(projectId: string, requestId: string, body: unknown, opts: RequestOptions = {}): Promise<WithdrawScopeExpansionResponse> {
  return request<WithdrawScopeExpansionResponse>("POST", `/projects/${projectId}/scope-expansions/${requestId}/withdraw`, body, opts);
}

